queue:
  send:
    connection:
    entityPath:
  listen:
    connection:
    entityPath:
  deadLetter:
    connection:
    entityPath:
topic:
  send:
    connection:
    entityPath:
  listen:
    connection:
    entityPath:

messages:
  factories:
    count: 3
  count: 1000
  batch:
    size: 100

logging:
  file: importing.log
  level:
    root: INFO